<a href="https://colab.research.google.com/github/Rezkydesyafa/ngulik-machine-learning_/blob/main/Dicoding_Regresi_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Belajar Machine Learning untuk Pemula

## Latihan Studi Kasus Regresi


Kita berjumpa pada bagian paling menyenangkan pada setiap modul yang ada, yaitu Latihan.

> *“Theory without practice is empty; Practice without theory is blind: The inherent inseparability of doctrine and skills”* —Harold Anthony Lloyd, Professor of Law at Wake Forest.

Untuk memenuhi kebutuhan ilmu machine learning tentunya teori saja tidaklah cukup. Ngomong-ngomong, apakah Anda menyadari sesuatu pada latihan modul dua mengenai machine learning workflow?

Wow ternyata Anda menyadari nya, ya. Benar, latihan yang disediakan pada modul dua merupakan permasalahan **regresi** yang mana studi kasus tersebut kita bahas lebih detail pada modul ini.

Karena pada kasus sebelumnya sudah membahas permasalahan terkait prediksi harga rumah, kita perlu mengganti studi kasus untuk latihan kali ini agar Anda mendapatkan pengalaman belajar yang lebih baik.

Data yang Anda gunakan pada proyek kali ini adalah **Flood Predictions** dataset yang diunduh dari repository Kaggle. Unduh dataset tersebut pada tautan berikut: Flood Predictions (tautan alternatif).

Untuk tahap latihan, Anda hanya akan menggunakan dataset ini sehingga tidak perlu menambahkan data lain atau melakukan penggabungan dataset lagi. Selain itu, dataset ini juga cukup bersih sehingga tidak terlalu banyak memerlukan proses data cleaning.

Dataset ini memiliki 815.044 baris data banjir dengan berbagai karakteristik. Karakteristik yang dimaksud di sini adalah fitur seperti `MoonsoonIntensity`, `TopographyDrainage`, `RiverManagement`, dan lain sebagainya.

Data ini memiliki 22 fitur, dengan 20 fitur di antaranya adalah fitur yang akan Anda gunakan dalam menemukan pola pada data, sedangkan `FloodProbability` merupakan fitur target.

Saat membangun model machine learning, Anda bebas menggunakan tools favorit seperti Google Colaboratory, Jupyter Notebook, atau Python Anaconda. Jika lebih nyaman menggunakan Python IDE (Integrated Development Environment), Anda bisa memilih PyCharm atau Visual Studio. Tak hanya itu, Anda juga bisa memanfaatkan notebook dari platform cloud, seperti IBM Watson Studio, Kaggle Kernel, atau Google Colab.

Agar setiap tahapan kode lebih mudah diikuti, proyek ini akan menggunakan Google Colaboratory. Bagaimana dengan Anda? Sudahkah Anda menentukan tools pilihan untuk proyek ini?

Jika sudah siap, mari kita mulai proses pembangunan model kita melalui beberapa langkah seperti pada modul dua.

---
### Data Loading
Agar dataset lebih mudah dipahami, langkah pertama yang perlu kita lakukan adalah memuat datanya. Jangan lupa untuk mengimpor library pandas agar kita bisa membaca file data.

Pada contoh kasus ini kita akan mengimpor data dari secara manual ke Google Colab. Kondisi ini terjadi ketika dataset ada di komputer lokal, Anda bisa mengunggahnya langsung ke file storage di Google Colab. Jika menggunakan tools lain atau menyimpan data di Google Drive, pastikan untuk menyesuaikan path data yang sesuai.

Langkah pertama, impor library yang diperlukan. Anda bisa melakukannya di awal, atau membaginya ke dalam sel kode sesuai kebutuhan.

In [16]:
import pandas as pd

df_train = pd.read_csv("/content/content/train.csv")
df_train

,id,MonsoonIntensity,TopographyDrainage,RiverManagement,Deforestation,Urbanization,ClimateChange,DamsQuality,Siltation,AgriculturalPractices,...,DrainageSystems,CoastalVulnerability,Landslides,Watersheds,DeterioratingInfrastructure,PopulationScore,WetlandLoss,InadequatePlanning,PoliticalFactors,FloodProbability
0,0,5,8,5,8,6,4,4,3,3,...,5,3,3,5,4,7,5,7,3,0.445
1,1,6,7,4,4,8,8,3,5,4,...,7,2,0,3,5,3,3,4,3,0.450
2,2,6,5,6,7,3,7,1,5,4,...,7,3,7,5,6,8,2,3,3,0.530
3,3,3,4,6,5,4,8,4,7,6,...,2,4,7,4,4,6,5,7,5,0.535
4,4,5,3,2,6,4,4,3,3,3,...,2,2,6,6,4,1,2,3,5,0.415
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1117952,1117952,3,3,4,10,4,5,5,7,10,...,7,8,7,2,2,1,4,6,4,0.495
1117953,1117953,2,2,4,3,9,5,8,1,3,...,9,4,4,3,7,4,9,4,5,0.480
1117954,1117954,7,3,9,4,6,5,9,1,3,...,5,5,5,5,6,5,5,2,4,0.485
1117955,1117955,7,3,3,7,5,2,3,4,6,...,6,8,5,3,4,6,7,6,4,0.495
1117956,1117956,4,5,6,9,5,5,2,8,4,...,4,8,6,5,5,6,7,7,8,0.560

Dapat Anda lihat pada output kode di atas bahwa data yang kita miliki memiliki **1.117.957 baris dengan 22 kolom**. Wow, jumlah data yang banyak ‘kan? Dengan jumlah yang sangat banyak ini bukan berarti materi ini ingin mempersulit Anda untuk belajar, tetapi justru sebaliknya. Materi ini ingin memberikan sedikit gambaran terkait jumlah data dan komputasi yang kelak akan Anda lakukan setiap hari di kantor impian!

Sebetulnya, Anda juga dapat memuat data test dengan menggunakan kode berikut.

In [19]:
df_test = pd.read_csv("/content/content/test.csv")
df_test

,id,MonsoonIntensity,TopographyDrainage,RiverManagement,Deforestation,Urbanization,ClimateChange,DamsQuality,Siltation,AgriculturalPractices,...,IneffectiveDisasterPreparedness,DrainageSystems,CoastalVulnerability,Landslides,Watersheds,DeterioratingInfrastructure,PopulationScore,WetlandLoss,InadequatePlanning,PoliticalFactors
0,1117957,4,6,3,5,6,7,8,7,8,...,8,5,7,5,6,3,6,4,4,5
1,1117958,4,4,2,9,5,5,4,7,5,...,2,4,7,4,5,1,7,4,4,3
2,1117959,1,3,6,5,7,2,4,6,4,...,7,9,2,5,5,2,3,6,8,3
3,1117960,2,4,4,6,4,5,4,3,4,...,7,8,4,6,7,6,4,2,4,4
4,1117961,6,3,2,4,6,4,5,5,3,...,4,3,2,6,4,6,8,4,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
745300,1863257,5,4,8,3,5,4,4,5,5,...,5,6,1,3,5,6,4,4,6,6
745301,1863258,4,4,2,12,4,3,4,3,5,...,3,7,4,4,3,5,5,3,5,4
745302,1863259,5,7,9,5,5,6,7,5,5,...,6,11,3,11,4,5,9,5,5,4
745303,1863260,4,7,6,3,5,2,3,8,6,...,6,6,8,6,2,3,8,7,5,5
745304,1863261,4,2,5,3,8,4,5,3,5,...,4,2,6,10,4,3,9,8,6,3

Jika Anda perhatikan data testing di atas tidaklah memiliki label atau target, hal ini bertujuan agar Anda dapat melakukan testing ketika model sudah berada di tahap produksi agar tidak terjadi error.

Hal ini menjadi wajar dalam situasi tertentu. Setelah model diuji dan dievaluasi, data testing tanpa label digunakan untuk membuat prediksi pada data baru yang belum diketahui. Data ini biasanya berasal dari dunia nyata sehingga model digunakan untuk membuat prediksi atau keputusan. Dalam kasus ini, memang tidak ada label karena data tersebut belum memiliki hasil aktual yang bisa dibandingkan.

---
### Data Cleaning dan Transformation
Kita akan melihat informasi dasar tentang dataset, seperti jumlah baris, kolom, tipe data, dan jumlah nilai yang hilang.

Pertama-tama, mari kita periksa tipe data dari masing-masing fitur yang ada di dataset. Tujuan dari pemeriksaan tipe data ini adalah untuk memastikan seluruh tipe data yang ada sudah sesuai dan tidak ada kekeliruan (contoh: data numerik terdeteksi str (string)). Sehingga, pada akhirnya Anda tidak akan mengalami kesulitan ketika melakukan preprocessing data karena tipe data yang ada sudah sesuai dan bisa melalui proses dengan lebih seamless.

In [ ]:
# Menampilkan ringkasan informasi dari dataset
df_train.info()

Selanjutnya, Anda perlu melakukan **analisis statistik deskriptif** dari dataset yang digunakan. Tujuan analisis statistik deskriptif dalam proses data cleaning pada machine learning adalah untuk memahami karakteristik dasar dari data yang sedang diproses.

Dengan melakukan analisis statistik deskriptif, kita bisa memastikan bahwa data yang digunakan untuk melatih model machine learning adalah data yang representatif, berkualitas tinggi, dan bebas dari masalah yang dapat memengaruhi hasil akhir. Berikut adalah contoh kode untuk melakukan analisis deskriptif.

In [ ]:
# Menampilkan statistik deskriptif dari dataset
df_train.describe(include="all")

Terakhir, Anda perlu melakukan pemeriksaan terhadap **data yang hilang (missing value)**. Tujuannya untuk mencegah kesalahan ketika melakukan analisis, mencegah error pada model, dan meningkatkan performa model. Dengan melakukan pemeriksaan missing value, Anda dapat memastikan bahwa proses analisis data dan pelatihan model machine learning berjalan dengan baik, sehingga hasil yang diperoleh lebih valid dan akurat. Berikut salah satu contoh kode untuk melakukan pemeriksaan missing value.

In [ ]:
missing_values = df_train.isnull().sum()
missing_values[missing_values > 0]

Seperti yang sudah diimbau pada awal materi ini, data yang Anda gunakan sudah tergolong bersih dan tidak memiliki missing value sehingga proses pembersihan data terlihat sangat mudah. Agar tantangannya semakin terasa, mari kita berpindah ke tahap berikutnya, yaitu **menangani outliers**.

Seperti yang Anda ketahui bahwa outliers merupakan salah satu blocker dalam membangun model machine learning yang optimal. Hal ini bisa disebabkan oleh berbagai hal seperti kesalahan pengisian data, error yang terjadi ketika pengumpulan data, dan lain sebagainya.

Salah satu metode yang efektif untuk mengatasi outlier adalah **Interquartile Range (IQR)**. Metode IQR mengukur sebaran data berdasarkan rentang antara kuartil pertama (Q1) dan kuartil ketiga (Q3). Nilai yang berada di bawah batas bawah (Q1 − 1,5 × IQR) atau di atas batas atas (Q3 + 1,5 × IQR) akan dianggap sebagai outlier.

Mari kita periksa terlebih dahulu apakah dataset yang digunakan memiliki outlier atau tidak menggunakan kode berikut.

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

for feature in df_train.columns:
    plt.figure(figsize=(10, 6))
    sns.boxplot(x=df_train[feature])
    plt.title(f'Box Plot of {feature}')
    plt.show()

Perhatikan visualisasi data di atas, apakah Anda dapat menyimpulkan sesuatu? Yup, nilai yang berada di bawah batas minimum atau di atas batas maksimum dianggap sebagai outlier. Ada dua pilihan yang biasa dilakukan untuk mengatasi permasalahan ini.
1. Anda dapat memilih untuk menghapus outlier.
2. Menggantinya dengan nilai yang lebih moderat (seperti batas terdekat), atau menerapkan transformasi.

Nah, pada kasus ini, kita akan memilih untuk menghapus data outlier dengan asumsi bahwa outlier yang terjadi merupakan human error dan tidak ada pengaruh yang besar pada analisis deskriptif. Mari kita mulai pemeriksaan outlier menggunakan metode IQR dengan menggunakan kode berikut.

In [ ]:
# Contoh sederhana untuk mengidentifikasi outliers menggunakan IQR
Q1 = df_train.quantile(0.25)
Q3 = df_train.quantile(0.75)
IQR = Q3 - Q1
# Filter dataframe untuk hanya menyimpan baris yang tidak mengandung outliers pada kolom numerik
condition = ~((df_train < (Q1 - 1.5 * IQR)) | (df_train > (Q3 + 1.5 * IQR))).any(axis=1)
df = df_train.loc[condition, df_train.columns]

Apakah Anda melihat perbedaannya? Benar sekali! Setelah penanganan outliers menggunakan IQR, distribusi data menjadi lebih merata dan terpusat, dengan mean dan median yang mendekati satu sama lain. Di lain sisi, varians dan standar deviasi akan berkurang, lalu rentang data menyusut karena nilai yang berbeda telah diatasi.

Jika Anda perhatikan, ketika melakukan analisis deskriptif di awal ada beberapa hal yang menarik seperti distribusi data yang berbeda, standar deviasi yang masih besar, hingga rentang data yang berbeda-beda. Nah, untuk mengatasi permasalahan tersebut, mari kita lakukan **standardisasi** pada data agar dapat mengoptimalkan proses pelatihannya kelak.

Berhubung seluruh tipe data yang ada pada dataset ini numerikal maka Anda tidak perlu melakukan transformasi atau pengubahan tipe data. Sehingga, pada tahapan standardisasi, kita bisa langsung memanggil library andalan, yaitu `StandardScaler`.

In [ ]:
from sklearn.preprocessing import StandardScaler

# Memastikan hanya data dengan tipe numerikal yang akan diproses
numeric_features = df.select_dtypes(include=['number']).columns
numeric_features

# Standardisasi fitur numerik
scaler = StandardScaler()
df[numeric_features] = scaler.fit_transform(df[numeric_features])

Dengan menggunakan kode di atas, Anda dapat mengubah distribusi data sehingga lebih baik dengan nilai standar deviasi kurang lebih mendekati satu.

Standardisasi penting untuk memastikan bahwa semua fitur dalam dataset memiliki skala yang sama sehingga mempermudah model untuk belajar dengan lebih baik dan memberikan hasil yang lebih akurat serta stabil.

Selanjutnya, Anda perlu memastikan bahwa data yang digunakan sudah bersih dengan **mengecek duplikasi data**.

In [ ]:
# Mengidentifikasi baris duplikat
duplicates = df.duplicated()

print("Baris duplikat:")
print(df[duplicates])

Seperti yang sudah dijelaskan pada awal materi ini, data yang Anda gunakan sudah tergolong bersih sehingga data ini tidak memiliki duplikasi atau nilai kosong.

Beralih ke tahap berikutnya, yaitu **exploratory dan explanatory data**. Pada tahap ini, Anda perlu meningkatkan kemampuan critical thinking agar dapat menggali informasi sedalam-dalamnya sehingga dapat memperoleh insight yang bermanfaat. Mari kita mulai dengan melihat karakteristik data yang sudah diolah sebelumnya.

In [ ]:
df.describe(include='all')

Data yang Anda miliki sudah memiliki distribusi yang cukup baik, hal tersebut dibuktikan dengan standar deviasi yang mendekati satu dan rentang nilai yang sama. Mari visualisasikan agar bentuknya terlihat lebih jelas.

In [ ]:
# Menghitung jumlah variabel
num_vars = df.shape[1]

# Menentukan jumlah baris dan kolom untuk grid subplot
n_cols = 4  # Jumlah kolom yang diinginkan
n_rows = -(-num_vars // n_cols)  # Ceiling division untuk menentukan jumlah baris

# Membuat subplot
fig, axes = plt.subplots(n_rows, n_cols, figsize=(20, n_rows * 4))

# Flatten axes array untuk memudahkan iterasi jika diperlukan
axes = axes.flatten()

# Plot setiap variabel
for i, column in enumerate(df.drop(columns=["id"]).columns):
    df[column].hist(ax=axes[i], bins=20, edgecolor='black')
    axes[i].set_title(column)
    axes[i].set_xlabel('Value')
    axes[i].set_ylabel('Frequency')

# Menghapus subplot yang tidak terpakai (jika ada)
for j in range(i + 1, len(axes)):
    fig.delaxes(axes[j])

# Menyesuaikan layout agar lebih rapi
plt.tight_layout()
plt.show()

Standardisasi yang Anda lakukan dapat membantu mengurangi efek bias atau skewness dari data yang tidak merata distribusinya. Dengan menempatkan fitur-fitur dalam skala yang sama, model machine learning lebih mudah untuk menemukan pola yang relevan seperti gambar di atas. Selain itu, ketika variabel-variabel berada pada skala yang berbeda secara signifikan, model machine learning mungkin menjadi tidak stabil dan memberikan hasil yang buruk. Standardisasi mengurangi risiko ini dengan membuat semua variabel berada dalam rentang yang konsisten.

Karena distribusi data yang Anda miliki sudah cukup baik, selanjutnya kita perlu memilih fitur yang memiliki hubungan dengan fitur target atau pada kasus ini adalah `FloodProbability`.

In [ ]:
# Menghitung korelasi antara variabel target dan semua variabel lainnya
target_corr = df.corr()['FloodProbability']

# (Opsional) Mengurutkan hasil korelasi berdasarkan kekuatan korelasi
target_corr_sorted = target_corr.abs().sort_values(ascending=False)

plt.figure(figsize=(10, 6))
target_corr_sorted.plot(kind='bar')
plt.title(f'Correlation with Flood Probability')
plt.xlabel('Variables')
plt.ylabel('Correlation Coefficient')
plt.show()

Sekali lagi, data yang kita gunakan pada kasus ini memang sudah dibuat sedemikian rupa sehingga fitur-fitur yang ada memang memiliki hubungan yang sama dengan fitur target. Lalu, apa artinya? Dengan adanya hubungan antara semua fitur dengan target, Anda tidak perlu menghilangkan fitur sehingga dataset ini siap untuk memasuki tahap selanjutnya, yaitu **splitting**.

Data splitting adalah langkah penting dalam workflow machine learning untuk memastikan bahwa model yang dibangun dapat digeneralisasikan dengan baik pada data yang belum pernah dilihat. Ini dapat menghindari bias evaluasi dan mengoptimalkan model dengan benar, dan memberikan estimasi kinerja yang lebih akurat. Mari kita split data menggunakan kode berikut.

In [ ]:
import sklearn
from sklearn import datasets

# Memisahkan fitur (X) dan target (y)
X = df.drop(columns=['FloodProbability'])
y = df['FloodProbability']

from sklearn.model_selection import train_test_split

# membagi dataset menjadi training dan testing
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

# menghitung panjang/jumlah data
print("Jumlah data: ",len(X))
# menghitung panjang/jumlah data pada x_train
print("Jumlah data latih: ",len(x_train))
# menghitung panjang/jumlah data pada x_test
print("Jumlah data test: ",len(x_test))

Dari sini kita bisa melihat bahwa dari jumlah data yang digunakan dapat dibagi menjadi dua subset yang berbeda dengan proporsi yang sudah ditentukan. Pada kasus ini kita akan menggunakan **676.708 data latih** dan **169.178 data testing**.

Dengan begitu data splitting memungkinkan kita untuk mengevaluasi kinerja model secara objektif. Dengan memisahkan data pelatihan dan pengujian, Anda bisa melihat seberapa baik model bekerja pada data yang belum pernah dilihat yang menyimulasikan kondisi dunia nyata. Ini membantu menghindari overfitting sehingga model dapat bekerja dengan sangat baik pada data pelatihan tetapi buruk pada data baru.

Selain itu, dengan membagi data menjadi bagian-bagian yang lebih kecil seperti set pelatihan dan set validasi memungkinkan Anda untuk menyetel hyperparameter model. Set validasi membantu dalam mengoptimalkan model tanpa memengaruhi data pengujian, yang sebaiknya hanya digunakan sekali untuk evaluasi akhir.

Setelah proses data splitting dilakukan langkah berikutnya dalam workflow machine learning adalah modelling. Proses ini melibatkan pelatihan model menggunakan set pelatihan yang telah kita siapkan, dan kemudian mengevaluasi kinerjanya dengan data pengujian atau validasi.

Setelah data terbagi, Anda dapat melatih model menggunakan training set. Model akan belajar dari fitur-fitur yang ada dalam data ini dan mencoba memetakan hubungan antara fitur dan target. Mari kita lakukan modelling atau pelatihan model menggunakan tiga algoritma yang berbeda.

---
### 1. LARS
Gunakan kode berikut untuk menerapkan LARS.

In [ ]:
from sklearn import linear_model
lars = linear_model.Lars(n_nonzero_coefs=1).fit(x_train, y_train)

pred_lars = lars.predict(x_test)

Setelah model dilatih Anda dapat menguji kinerja model pada data validasi. Proses ini penting agar model tidak hanya optimal pada data pelatihan, tetapi juga bekerja dengan baik pada data baru.

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
mae_lars = mean_absolute_error(y_test, pred_lars)
mse_lars = mean_squared_error(y_test, pred_lars)
r2_lars = r2_score(y_test, pred_lars)

print(f"MAE: {mae_lars}")
print(f"MSE: {mse_lars}")
print(f"R²: {r2_lars}")

Bagaimana apakah Anda sudah puas dengan performa model yang dibangun? Jika belum mari kita bandingkan dengan algoritma lainnya.

Nah, agar Anda dapat membandingkan ketiga model yang akan dibangun, mari kita buat sebuah DataFrame seperti berikut.

In [ ]:
# Membuat dictionary untuk menyimpan hasil evaluasi
data = {
    'MAE': [mae_lars],
    'MSE': [mse_lars],
    'R2': [r2_lars]
}

# Konversi dictionary menjadi DataFrame
df_results = pd.DataFrame(data, index=['Lars'])
df_results

Selanjutnya, lakukanlah hal yang sama terhadap algoritma lainnya.

### 2. Linear Regression
Gunakan kode berikut untuk menerapkan Linear Regression.

In [ ]:
from sklearn.linear_model import LinearRegression
LR = LinearRegression().fit(x_train, y_train)

pred_LR = LR.predict(x_test)

mae_LR = mean_absolute_error(y_test, pred_LR)
mse_LR = mean_squared_error(y_test, pred_LR)
r2_LR = r2_score(y_test, pred_LR)

print(f"MAE: {mae_LR}")
print(f"MSE: {mse_LR}")
print(f"R²: {r2_LR}")

Dari sini sudah terlihat jelas perbedaan performa yang dihasilkan, tetapi untuk membuktikan ini yang terbaik mari kita bandingkan dengan salah satu algoritma lainnya.

In [ ]:
df_results.loc['Linear Regression'] = [mae_LR, mse_LR, r2_LR]
df_results

### 3. Gradient Boosting Regressor
Gunakan kode berikut untuk menerapkan GradientBoostingRegressor.

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor

GBR = GradientBoostingRegressor(random_state=184)
GBR.fit(x_train, y_train)

pred_GBR = GBR.predict(x_test)

mae_GBR = mean_absolute_error(y_test, pred_GBR)
mse_GBR = mean_squared_error(y_test, pred_GBR)
r2_GBR = r2_score(y_test, pred_GBR)

print(f"MAE: {mae_GBR}")
print(f"MSE: {mse_GBR}")
print(f"R²: {r2_GBR}")

Dari sini, Anda sudah membandingkan beberapa algoritma. Langkah terakhir Anda perlu membandingkan ketiga model dan memilih model dengan performa terbaik.

In [ ]:
df_results.loc['GradientBoostingRegressor'] = [mae_GBR, mse_GBR, r2_GBR]
df_results

---
### Evaluasi Akhir
Seperti yang dapat Anda lihat pada hasil di atas, algoritma **Linear Regression** memiliki nilai evaluasi yang lebih baik jika dibandingkan dengan GradientBoostingRegressor. Mengapa hal itu bisa terjadi? Ada beberapa alasan mengapa algoritma Linear Regression dapat bekerja lebih baik daripada GradientBoostingRegressor dalam beberapa kasus meskipun Gradient Boosting adalah algoritma ensemble yang lebih kompleks.

Salah satu alasannya adalah data yang Anda gunakan memiliki hubungan sederhana antara fitur dan target atau bisa disebut **linearitas**.

Jika hubungan antara fitur dan target bersifat linear atau hampir linear, Linear Regression mungkin akan bekerja lebih baik. Linear Regression didesain untuk menangani hubungan linear secara optimal dan tidak membutuhkan model yang kompleks untuk menemukan pola tersebut. Sebaliknya, GradientBoostingRegressor adalah model non-linear yang mencoba menangkap pola yang lebih rumit. Jika hubungan antara variabel sangat sederhana dan linear, model ini akan terlalu kompleks (overfitting) dan memberikan hasil yang lebih buruk.

Pada dasarnya, pemilihan algoritma yang tepat sangat bergantung pada karakteristik dataset dan masalah yang sedang dihadapi. Meskipun GradientBoostingRegressor secara teori lebih kuat dan fleksibel, tetapi dalam kasus tertentu Linear Regression bisa menjadi pilihan yang lebih tepat karena kesederhanaan dan kemampuan generalisasi yang lebih baik pada dataset sederhana. *So*, jangan asal memilih algoritma karena ingin terlihat lebih keren, ya!

### Kesimpulan
Anda telah menempuh perjalanan yang luar biasa dalam memahami regresi pada modul ini. Dimulai dari mengenal dasar-dasar Linear Regression hingga menyelami model-model yang lebih kompleks seperti GradientBoostingRegressor, Anda telah membuka pintu menuju salah satu fondasi paling penting dalam dunia machine learning dan analisis data. Tidak hanya sekadar memahami teori, tetapi Anda juga sudah belajar bagaimana menerapkannya dalam kode, melihat hasilnya, dan mengevaluasi kinerja model.

Satu hal yang pasti: belajar machine learning, khususnya regresi adalah sebuah petualangan yang tak pernah berakhir. Anda tidak hanya belajar pengetahuan baru, tetapi juga cara berpikir yang baru—cara berpikir yang memungkinkan Anda untuk mengubah data menjadi wawasan yang berarti. Itulah yang menjadikan perjalanan ini begitu mengasyikkan dan bermanfaat.

Tetaplah penasaran. Tantang diri Anda dengan proyek baru. Jangan takut untuk membuat kesalahan—itulah bagian dari proses belajar yang sesungguhnya. Setiap percobaan dan latihan membawa Anda lebih dekat kepada keahlian dan pemahaman yang lebih mendalam.

Selamat melanjutkan perjalanan di dunia data dan machine learning! Setiap langkah kecil yang Anda ambil akan membuka pintu menuju peluang yang lebih besar di masa depan. Semoga semangat belajar Anda tetap menyala dan terus tumbuh seiring bertambahnya pengetahuan dan pengalaman, ya!